name: Deploy thesis word count to Pages

on:
  # Runs every 30 minutes
  schedule:
    - cron: '*/30 * * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Checkout LaTeX project
      run: git clone https://$HTTP_USERNAME:$HTTP_TOKEN@$HTTP_REPO_URL latex_project
      env:
        HTTP_USERNAME: ${{ secrets.HTTP_USERNAME }}
        HTTP_TOKEN: ${{ secrets.HTTP_TOKEN }}
        HTTP_REPO_URL: ${{ secrets.HTTP_REPO_URL }}

    - name: Install LaTeX
      run: sudo apt-get install -y texlive texlive-latex-extra texlive-fonts-recommended biber poppler-utils

    - name: Build PDF
      run: | 
        cd latex_project
        pdflatex -interaction=nonstopmode main.tex
        biber main
        pdflatex -interaction=nonstopmode main.tex
      
    - name: Count Words in PDF and build html
      run: |
        WORD_COUNT=$(pdftotext latex_project/main.pdf - | wc -w)
        find "website" -type f -exec sed -i "s/WORD_COUNT/${WORD_COUNT}/g" {} +

    - name: Fix permissions
      run: |
        chmod -c -R +rX "website/" | while read line; do
          echo "::warning title=Invalid file permissions automatically fixed::$line"
        done
        
    - uses: actions/upload-pages-artifact@v2
      with:
        path: website/
        
  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    permissions:
        pages: write
        id-token: write
        
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
    - name: Deploy artifact
      id: deployment
      uses: actions/deploy-pages@v2
